## Generate correct .bin file for 7000 SoCs.
# See here: https://github.com/amaranth-lang/amaranth/issues/519
# This overwrites the 'wrong' .bin file generated by default. To copy the .bin
# file to the images directory, also make sure to set 
# export GEN_BIN_IMAGE = 1
# in for example `shared_version.mk`.

set IMPL_DIR         $::env(IMPL_DIR)
set IMAGES_DIR       $::env(IMAGES_DIR)

set topModule [file rootname [file tail [glob -dir ${IMPL_DIR} *.bit]]]

write_cfgmem -force -format bin -interface smapx32 -disablebitswap -loadbit "up 0 ${IMPL_DIR}/${topModule}.bit" ${IMPL_DIR}/${topModule}.bin

set imagePath "${IMAGES_DIR}/$::env(IMAGENAME)"

exec cp -f ${IMPL_DIR}/${topModule}.bin ${imagePath}.bin
puts ">>> Bin file (for 7000 SoCs) copied to ${imagePath}.bin"
